AWSTemplateFormatVersion: '2010-09-09'
Description: 'Master Stack for CareFlowAI - Complete Infrastructure with ASG, ALB, and CloudWatch'

Parameters:
  EnvironmentName:
    Description: Environment name prefix
    Type: String
    Default: CareFlowAI

  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: t3.small
    AllowedValues:
      - t3.small
      - t3.medium
      - t3.large

  KeyName:
    Description: EC2 Key Pair for SSH access
    Type: AWS::EC2::KeyPair::KeyName

  MongoDBURL:
    Description: MongoDB connection URL (e.g., MongoDB Atlas)
    Type: String
    NoEcho: true

  GeminiAPIKey:
    Description: Google Gemini API Key
    Type: String
    NoEcho: true

  SecretKey:
    Description: JWT Secret Key (generate a strong random key)
    Type: String
    NoEcho: true
    Default: change-this-to-a-secure-random-key-in-production

  AlarmEmail:
    Description: Email address for CloudWatch alarms
    Type: String
    Default: admin@example.com

  MinSize:
    Description: Minimum number of instances in ASG
    Type: Number
    Default: 1

  MaxSize:
    Description: Maximum number of instances in ASG
    Type: Number
    Default: 3

  DesiredCapacity:
    Description: Desired number of instances in ASG
    Type: Number
    Default: 1

Resources:
  # VPC Stack
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://careflowai-cloudformation-templates-1764620270.s3.us-east-1.amazonaws.com/vpc.yaml
      Parameters:
        EnvironmentName: !Ref EnvironmentName
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-VPC-Stack

  # Application Load Balancer Stack
  ALBStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: VPCStack
    Properties:
      TemplateURL: https://careflowai-cloudformation-templates-1764620270.s3.us-east-1.amazonaws.com/alb.yaml
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        VPCId: !GetAtt VPCStack.Outputs.VPC
        PublicSubnet1: !GetAtt VPCStack.Outputs.PublicSubnet1
        PublicSubnet2: !GetAtt VPCStack.Outputs.PublicSubnet2
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-ALB-Stack

  # Auto Scaling Group Stack
  ASGStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: ALBStack
    Properties:
      TemplateURL: https://careflowai-cloudformation-templates-1764620270.s3.us-east-1.amazonaws.com/asg.yaml
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        InstanceType: !Ref InstanceType
        KeyName: !Ref KeyName
        VPCId: !GetAtt VPCStack.Outputs.VPC
        PublicSubnet1: !GetAtt VPCStack.Outputs.PublicSubnet1
        PublicSubnet2: !GetAtt VPCStack.Outputs.PublicSubnet2
        BackendSecurityGroup: !GetAtt ALBStack.Outputs.BackendSecurityGroup
        TargetGroupArn: !GetAtt ALBStack.Outputs.BackendTargetGroup
        MinSize: !Ref MinSize
        MaxSize: !Ref MaxSize
        DesiredCapacity: !Ref DesiredCapacity
        MongoDBURL: !Ref MongoDBURL
        GeminiAPIKey: !Ref GeminiAPIKey
        SecretKey: !Ref SecretKey
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-ASG-Stack

  # CloudWatch Monitoring Stack
  CloudWatchStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: ASGStack
    Properties:
      TemplateURL: https://careflowai-cloudformation-templates-1764620270.s3.us-east-1.amazonaws.com/cloudwatch.yaml
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        AutoScalingGroupName: !GetAtt ASGStack.Outputs.AutoScalingGroupName
        LoadBalancerFullName: !Select [1, !Split ['/', !GetAtt ALBStack.Outputs.LoadBalancerArn]]
        TargetGroupFullName: !Select [1, !Split [':', !Select [5, !Split [':', !GetAtt ALBStack.Outputs.BackendTargetGroup]]]]
        AlarmEmail: !Ref AlarmEmail
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-CloudWatch-Stack

Outputs:
  LoadBalancerDNS:
    Description: Application Load Balancer DNS Name - Use this for your API endpoint
    Value: !GetAtt ALBStack.Outputs.LoadBalancerDNS

  APIURL:
    Description: API Base URL
    Value: !Sub http://${ALBStack.Outputs.LoadBalancerDNS}

  HealthCheckURL:
    Description: Health Check URL
    Value: !Sub http://${ALBStack.Outputs.LoadBalancerDNS}/health

  DocsURL:
    Description: API Documentation URL
    Value: !Sub http://${ALBStack.Outputs.LoadBalancerDNS}/docs

  AutoScalingGroupName:
    Description: Auto Scaling Group Name
    Value: !GetAtt ASGStack.Outputs.AutoScalingGroupName

  DashboardURL:
    Description: CloudWatch Dashboard URL
    Value: !GetAtt CloudWatchStack.Outputs.DashboardURL

  VPCId:
    Description: VPC ID
    Value: !GetAtt VPCStack.Outputs.VPC

  BackendLogGroup:
    Description: CloudWatch Logs Group for Backend
    Value: !GetAtt CloudWatchStack.Outputs.BackendLogGroupName
