AWSTemplateFormatVersion: '2010-09-09'
Description: 'S3 and CloudFront for CareFlowAI Frontend'

Parameters:
  EnvironmentName:
    Description: Environment name prefix
    Type: String
    Default: CareFlowAI

  DomainName:
    Description: Custom domain name (optional)
    Type: String
    Default: ''

Resources:
  # S3 Bucket for Frontend
  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::AccountId}-careflowai-frontend
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
      VersioningConfiguration:
        Status: Suspended
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-Frontend-Bucket

  # S3 Bucket Policy
  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Sub ${FrontendBucket.Arn}/*

  # CloudFront Origin Access Identity
  CloudFrontOAI:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub OAI for ${EnvironmentName}

  # CloudFront Distribution
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        HttpVersion: http2
        DefaultRootObject: index.html
        Comment: !Sub ${EnvironmentName} Frontend Distribution

        Origins:
          # S3 Origin (Frontend)
          - Id: S3Origin
            DomainName: !GetAtt FrontendBucket.RegionalDomainName
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: http-only

        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
            - OPTIONS
          Compress: true
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none

        CustomErrorResponses:
          # Handle React Router (404 errors)
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
            ErrorCachingMinTTL: 10

          # Handle React Router (403 errors)
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
            ErrorCachingMinTTL: 10

        PriceClass: PriceClass_100

      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-CloudFront

Outputs:
  FrontendBucketName:
    Description: S3 Bucket Name
    Value: !Ref FrontendBucket
    Export:
      Name: !Sub ${EnvironmentName}-FrontendBucket

  FrontendBucketURL:
    Description: S3 Website URL
    Value: !GetAtt FrontendBucket.WebsiteURL
    Export:
      Name: !Sub ${EnvironmentName}-FrontendURL

  CloudFrontDistributionId:
    Description: CloudFront Distribution ID
    Value: !Ref CloudFrontDistribution
    Export:
      Name: !Sub ${EnvironmentName}-CloudFrontId

  CloudFrontDomainName:
    Description: CloudFront Domain Name
    Value: !GetAtt CloudFrontDistribution.DomainName
    Export:
      Name: !Sub ${EnvironmentName}-CloudFrontDomain
